repositories:
# Cloud Posse incubator repo of helm charts
- name: "cloudposse-incubator"
  url: "https://charts.cloudposse.com/incubator/"

releases:

#######################################################################################
## Atlantis                                                                          ##
#######################################################################################

#
# References:
#   - https://github.com/cloudposse/atlantis/tree/master/helm/atlantis
#   - https://github.com/cloudposse/charts/blob/master/incubator/monochart
#
- name: "blue-example"
  namespace: "example"
  labels:
    color: "blue"
  chart: "cloudposse-incubator/monochart"
  version: "0.7.0"
  wait: true
  force: true
  recreatePods: false
  values:
    - fullnameOverride: atlantis
      image:
        repository: '{{ env "IMAGE_NAME" | default "cloudposse/example-app" }}'
        tag: '{{ env "IMAGE_TAG" | default "0.1.0" }}'
        pullPolicy: Always
        pullSecrets:
          - 'atlantis-pull-secret-dockercfg'

      configMaps:
        default:
          enabled: true
          env:
            # Color to deploy
            COLOR: "cyan"

      service:
        enabled: true
        type: ClusterIP
        ports:
          default:
            internal: 8080
            external: 80

      ingress:
        default:
          enabled: true
          labels:
            dns: "route53"
          annotations:
            kubernetes.io/ingress.class: nginx
            kubernetes.io/tls-acme: "true"
            external-dns.alpha.kubernetes.io/target: '{{ requiredEnv "NGINX_INGRESS_HOSTNAME" }}'
            external-dns.alpha.kubernetes.io/ttl: "60"
          hosts:
            ### Required: ATLANTIS_HOSTNAME;
            '{{ env "ATLANTIS_HOSTNAME" }}': /
          tls:
              ### Optional: ATLANTIS_TLS_SECRET_NAME;
            - secretName: '{{ env "ATLANTIS_TLS_SECRET_NAME" | default "atlantis-server-tls" }}'
              hosts:
              ### Required: ATLANTIS_HOSTNAME;
              - '{{ env "ATLANTIS_HOSTNAME" }}'
      
      probes:
        livenessProbe:
          httpGet:
            path: /healthz
            port: default
            scheme: HTTP
          periodSeconds: 60
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          scheme: HTTP
        readinessProbe:
          httpGet:
            path: /healthz
            port: default
            scheme: HTTP
          periodSeconds: 60
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5

      resources:
        requests:
          memory: 1Gi
          cpu: 100m
        limits:
          memory: 1Gi
          cpu: 100m