version: '1.0'

stages:
  - Prepare
  - Build
  - Push
  - Deploy

steps:
  main_clone:
    title: "Clone repository"
    type: git-clone
    stage: Prepare
    description: "Initialize"
    repo: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
    git: CF-default
    revision: ${{CF_REVISION}}

  build_image:
    title: Build image
    stage: Build
    type: build
    description: Build image
    image_name: ${{CF_DOCKER_REPO_URL}}/${{CF_REPO_NAME}}
    dockerfile: Dockerfile

  push_image_commit:
    title: Push image with commit tag
    stage: Push
    type: push
    candidate: ${{build_image}}
    registry: dockerhub
    tags:
    - "${{CF_REVISION}}"

  deploy_master:
    title: Deploying to Master
    stage: "Deploy"
    image: 'codefresh/cli:latest'
    environment:
      STAGE: master
    commands:
      - codefresh run ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}/deploy-${{STAGE}} -d -b=${{CF_BRANCH}} -v CF_RELEASE_TAG=${{CF_REVISION}} -v CF_PRERELEASE_FLAG=${{CF_PRERELEASE_FLAG}} -v STAGE=${{STAGE}}
    when:
      branch:
        only:
          - master