version: '1.0'

stages:
  - Promote
  - Deploy Staging
  - Deploy Production

steps:
  main_clone:
    title: "Prepare Release"
    stage: "Promote"
    image: alpine
    commands:
      - echo "Preparing Deployment of ${{CF_REVISION}} (${{CF_REVISION}})"

  pull_image_sha:
    title: Pull image with commit SHA
    stage: "Promote"
    image: "${{CF_DOCKER_REPO_URL}}/${{CF_REPO_NAME}}:${{CF_REVISION}}"
    retry:
      maxAttempts: 10
      delay: 20
      exponentialFactor: 1.1
    commands:
    - "true"

  push_image_tag:
    title: Push image with release tag
    stage: "Promote"
    type: push
    image_name: ${{CF_REPO_NAME}}
    candidate: "${{CF_DOCKER_REPO_URL}}/${{CF_REPO_NAME}}:${{CF_REVISION}}"
    registry: dockerhub
    tags:
    - "${{CF_RELEASE_TAG}}"

  deploy:
    title: Deploy Release
    stage: "Deploy"
    image: 'codefresh/cli:latest'
    environment:
      STAGE: staging
    commands:
      - codefresh run ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}/deploy-${{STAGE}} -d -b=${{CF_BRANCH}} -v CF_RELEASE_TAG=${{CF_RELEASE_TAG}} -v CF_PRERELEASE_FLAG=${{CF_PRERELEASE_FLAG}} -v STAGE=${{STAGE}}

  deploy:
    title: Deploy Release to Production
    stage: "Deploy Production"
    image: 'codefresh/cli:latest'
    environment:
      STAGE: prod
    commands:
      - codefresh run ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}/deploy-${{STAGE}} -d -b=${{CF_BRANCH}} -v CF_RELEASE_TAG=${{CF_RELEASE_TAG}} -v CF_PRERELEASE_FLAG=${{CF_PRERELEASE_FLAG}} -v STAGE=${{STAGE}}